### PR TITLE
added flawcode json

### PR DESCRIPTION
**Pull request by infinite-Joy**

### CODE REVIEW

**Comment by szabgab** [comment]
great, please also update sources.json to include flawcode

**Comment by infinite-Joy** [comment]
updated sources json file

**Comment by szabgab** [comment]
Thanks.  One more issue: Each person (both hosts and guests) need a file in data/people/ with their name, github, twitter, home (url) and contry.
Try running ```python3 xcast.py --html to generate the site locally.

**Comment by infinite-Joy** [comment]
I made some more commits and now am able to run the command ```python3 xcast.py --html``` without any errors

**Comment by szabgab** [comment]
Thanks. merged and published.

**Pull request merged**
